/*Karen González Ramírez 22110358
Rafael Martinez Cerda 22110385 
Proyecto de Gauss-Seidel 
16 de Junio del 2023*/

@startuml sidel 

class GaussSeidel{
+Int main
}

class GaussSeidelSolver{
-Matriz A   
-Matriz B
-Vector X
-Interaciones
-Tolerancia
+Vector Resolver(Vector cero)
+Vector Cero
}

GaussSeidel*--GaussSeidelSolver

@enduml